### ISSUE TITLE
App requires restart to receive transation

### ISSUE THREAD

**Issue by 0x3639** [drblazer21/syrius_mobile#10]
Issue: When I send a [TX](https://zenonhub.io/explorer/account/z1qprw42as8dd7hstf38n7q2fcvln6rkmjy4ww3n) to the mobile app is does not receive the transaction.  App must be restarted to receive the transaction.

Steps to reproduce:
- uninstall old version of the app
- install latest version (https://workupload.com/file/Jg3TrtwmbZJ)
- setup new wallet.  Note I have NOT backed up the wallet at this point.
- send TX from another address to mobile wallet.
- mobile wallet does not receive the transaction. Note: no plasma (QSR) was fused on the mobile wallet address
- stop mobile wallet
- start mobile wallet
- mobile wallet then automagically receives the transaction
- I sent another test TX to the mobile wallet and got the same result.  The mobile wallet requires a restart to receive the TX.  I tried to refresh the wallet page by pulling down.  I saw the refresh button but the only way to receive the TX was to restart the wallet another time. 
- Finally I fused QSR to the mobile wallet address and sent 0.01 ZNN there and the mobile wallet will not auto receive it.  I tried to pull down to refresh and that did not work. The only way to receive the TX is to reboot the mobile wallet app.

**Comment by 0x3639** [comment]
I also wanted to note three "strange" behaviors:

1) When you receive a transaction on the mobile wallet when plasma is already fused to the address, the popup message says Plasma is being generated.  I recommend you change this message as plasma is not being generated.  It's already fused.
2) after you send a TX from the mobile wallet the values (amount and address) are removed but the keyboard remains open.  It gives you the impression that the TX was not sent / successful.  I recommend after a successful TX being sent you hide the keyboard and display the message the TX was sent successfully or Plasma is being generated to send the TX.  
3) We need a way to copy addresses from the Activity screen.  When someone send you a TX we need the ability to copy their address from the activity screen to easily send them funds back.

**Comment by drblazer21** [comment]
@0x3639 all issues are fixed and all the suggestions are implemented in [v0.5.2](https://github.com/drblazer21/syrius_mobile/releases/tag/v0.5.2-alphanet).
