### ISSUE TITLE
feat: load community nodes from assets

### ISSUE THREAD

**Issue by KingGorrin** [drblazer21/syrius_mobile#2]
**Describe the solution you'd like**
As of syrius v0.2.0 community nodes are retrieved from the [zenon node database](https://github.com/hypercore-one/zenon-node-database) on build and stored in an asset file.

This allow the community to centrally manage which nodes to add or remove in future releases by submitting PR to the Zenon Node Database.

The syrius mobile wallet can implement the same mechanism with the exception of the default node in case the asset file is empty.

**Additional context**
- See this [PR](https://github.com/zenon-network/syrius/pull/69) for the impl. in syrius.

**Comment by drblazer21** [comment]
Feel free to create a PR with the implementation and I'll merge it. Thank you!
