### ISSUE TITLE
Notification messages hide buttons

### ISSUE THREAD

**Issue by KingGorrin** [drblazer21/syrius_mobile#3]
**Describe the bug**
Notification messages hide buttons.

**To Reproduce**

1. Go to 'Settings'
2. Click on 'Node Management'
3. Click on 'Add node'
4. Enter node and click on the `Add node` button
5. Go to `Node Selection`
6. Select added node
7. Save button is not visible

**Expected behavior**
A save button to be visible to save the new node selection.

**Actual behavior**
The notification message is obscuring the save button.

**Workaround**
The notification message needs to be dismissed by swiping it down. Which not very obvious at first.

**Screenshots**
![syrius-mobile-node-selection](https://github.com/drblazer21/syrius_mobile/assets/13164589/c249c2c2-690d-4e52-8d4f-8a5dfb2af5e1)

**Mobile:**
- OS: Android 14
- App Version: v0.2.3
- Commit hash: 44c191551c524ad16f97228f6a3e059a4df506dc

**Additional context**
The same can also happen in other screens which have a button at the button, like fusing and sending.

**Comment by drblazer21** [comment]
Thank you for the UX feedback. Snackbars can be replaced with MaterialBanners in those cases. Closing this for now.
