### ISSUE TITLE
Cannot fuse QSR on Android

### ISSUE THREAD

**Issue by KingGorrin** [drblazer21/syrius_mobile#4]
**Describe the bug**
Cannot fuse QSR on Android. Zenon SDK Exception: Library libpow_links could not be found.

**To Reproduce**

1. Go to 'Fuse'
2. Enter amount and address
3. Click fuse

**Expected behavior**
The QSR is fused after PoW is generated.

**Actual behavior**
The QSR is not fused, fuse icon keeps spinning and error notifications are displayed.

**Screenshots**
![syrius-mobile-fuse-error](https://github.com/drblazer21/syrius_mobile/assets/13164589/d2b0db94-6312-4d09-ad27-926e220148c3)

**Mobile:**
- OS: Android 14
- App Version: v0.2.3
- Commit hash: 44c191551c524ad16f97228f6a3e059a4df506dc

**Additional context**
The application has been custom build and manually installed.

**Comment by drblazer21** [comment]
How did you build the app and for what architecture? For Android only `x86_64` and `arm64-v8a` architectures are supported.

**Comment by KingGorrin** [comment]
I'm running the app on a Samsung Exynos 2200 processor.

> the Samsung Exynos 2200 SoC is a 64-bit ARM-based processor, it’s designed by Samsung and co-developed with AMD. It features an AMD “Xclipse” GPU and supports ARM64 architecture

I've build the app using an explicit target platform: `flutter build apk --target-platform android-arm64 --release`

Checked that the resulting APK file had both the `libpow_links.so` file included in both the `lib/arm64-v8a` and `lib/x86_64` directory.

Cleared the cache and uninstalled the app completely before installing the APK file.

**Comment by drblazer21** [comment]
[Fixed](https://github.com/drblazer21/znn_sdk_dart/commit/34d441b6af409c99e133ac38c9a3154a026d2a63). Please test again the app and feel free to close the issue if it works.

**Comment by KingGorrin** [comment]
PoW is working now, issue can be closed.
