### ISSUE TITLE
Cannot import wallet with double word seed phrase

### ISSUE THREAD

**Issue by KingGorrin** [drblazer21/syrius_mobile#5]
**Describe the bug**
Cannot import wallet when the seed phrase contains a double seed word.

**To Reproduce**

1. Open app
2. Click on 'import wallet'
3. Try to enter a seed phrase that has a double word

**Expected behavior**
All words are recognized and can be entered.

**Actual behavior**
The second double word is not recognized and cannot be entered.

**Workaround**
Create a new seed phrase that does not contain double words.

**Syrius Mobile**
- OS: android-arm64
- Version: 0.2.3

**Comment by drblazer21** [comment]
Fixed in [v0.5.2](https://github.com/drblazer21/syrius_mobile/releases/tag/v0.5.2-alphanet).
