### ISSUE TITLE
Stuck loading after enabling Secure Enclave protection

### ISSUE THREAD

**Issue by KingGorrin** [drblazer21/syrius_mobile#7]
The app got stuck when enabling the Secure Enclave protection.

**To Reproduce**
1. Uninstall previous version
2. Install v0.3.0
3. Import existing or create new wallet
4. Set and confirm PIN
5. Enabled Secure Enclave protection (default) and click continue
6. Supply biometry

**Expected behavior**
Continue to next view

**Actual behavior**
Nothing happens, loading icons keeps spinning

**Syrius Mobile**
- Version: v0.3.0
- OS: Android 14, Samsung Galaxy S24

**Workaround**
Close app, open and enter PIN.

**Comment by drblazer21** [comment]
Fixed in [v0.5.2](https://github.com/drblazer21/syrius_mobile/releases/tag/v0.5.2-alphanet).
