### ISSUE TITLE
Cannot delete wallet

### ISSUE THREAD

**Issue by KingGorrin** [drblazer21/syrius_mobile#8]
The delete wallet settings option does not seem to work.

**To Reproduce**
1. Open app
2. Goto "Settings"
3. Select "Delete wallet"
4. Enter PIN
5. Proceed and click "Delete wallet" button
6. Wait for the delete timer to expire
7. Click "Delete" button to confirm

**Expected behavior**
Wallet is deleted

**Actual behavior**
Nothing happens and delete timer is restarted until it expires and the "Delete" button can be pressed again.

The wallet seems to be in a bad state after having pressed the "Delete" button. When returning to the settings screen and selecting the "Delete wallet" again, entering the PIN code results in the following error.

`Invalid argument *data). Less than minimum length (12 + 16). _Uint8List`

**Syrius Mobile**
- Version: v0.3.0
- OS: Android 14, Samsung Galaxy S24

**Workaround**
Uninstall app using Android.

**Comment by drblazer21** [comment]
Fixed in [v0.5.2](https://github.com/drblazer21/syrius_mobile/releases/tag/v0.5.2-alphanet).
