### ISSUE TITLE
Cannot select words when confirming seed when using increased font size

### ISSUE THREAD

**Issue by KingGorrin** [drblazer21/syrius_mobile#9]
Only 4 of the 12 words can be selected in the Confim Seed view when confirming the 12 words seed. The remaining words fall outside of the screen and cannot be selected when using an increased font size.

**To Reproduce**
1. Increase mobile font size
1. Open app
1. Goto "Settings"
1. Select "Seed backup"
1. Enter PIN
1. Select "Press and Hold to Reveal"
1. Select "Continue"

**Expected behavior**
All 12 words can be selected.

**Actual behavior**
Only 4 of the 12 words can be selected.

**Syrius Mobile**
- Version: v0.4.0
- OS: Android 14, Samsung Galaxy S24

**Workaround**
Reset default font-size and backup seed.

**Comment by KingGorrin** [comment]
This is also an issue when using a 24 words seed phrase. The remaining words fall outside of the screebn, even with normal font-size.

**Comment by drblazer21** [comment]
Fixed in [v0.5.2](https://github.com/drblazer21/syrius_mobile/releases/tag/v0.5.2-alphanet).
